### ISSUE TITLE
使用https访问网页无法播放

### ISSUE THREAD

**Issue by Eatsolx** [kjtsune/embyToLocalPlayer#12]
MacOS下IINA可以播放http，无法播放https

**Comment by kjtsune** [comment]
若日志正常有显示调用，都是命令行启动播放器播放的，理论无区别。关闭模糊日志。手动用终端播放试试看。

**Comment by kjtsune** [comment]
点油猴插件，关闭读盘模式。

**Comment by Eatsolx** [comment]
关闭读盘模式后解决。关闭读盘模式会缺失什么功能吗？
