### ISSUE TITLE
控制台运行出现异常

### ISSUE THREAD

**Issue by Tesla-AC** [kjtsune/embyToLocalPlayer#15]
平台：x64
系统：Win10 22H2 内部版本：19045.3324
问题：双击 embyToLocalPlayer_debug.bat 无报错，按按1（窗口运行）时出现异常，异常信息如下
![image](https://github.com/kjtsune/embyToLocalPlayer/assets/56549504/d5f25a7f-23c8-4f2c-b2d7-09c2a61cb61e)

**Comment by Tesla-AC** [comment]
经测试，更换python 3.8.10 版本依旧出现同样问题

**Comment by kjtsune** [comment]
编码问题，命令行试一下下面的命令，看输出正常吗。
`powershell -Command 'Get-WmiObject Win32_Process | Select ProcessId,CommandLine | ConvertTo-Json'`

**Comment by kjtsune** [comment]
修改 utils/windows_tool.py 后测试，不懂操作就看faq加群发文件给你测试
```
    default_encoding = locale.getpreferredencoding()
    # encoding = 'gbk' if default_encoding == 'cp936' else 'utf-8'
    cmd = 'Get-WmiObject Win32_Process | Select ProcessId,CommandLine | ConvertTo-Json'
    try:
        proc = subprocess.run(['powershell', '-Command', cmd], capture_output=True,
                              encoding=default_encoding) # default_encoding 换成 'utf-8' 之类的，试试看
    except FileNotFoundError:
        raise FileNotFoundError('powershell not found in cmd, check sys and user environment path') from None
    if proc.returncode != 0:
        return []
    print(proc.stdout) # 加这行看看，是否打印正常
```

**Comment by kjtsune** [comment]
也可以改配置文件，简单快速。 dev > kill_process_at_start = no
但是这样子你想重启脚本的时候，要先去任务管理器杀死旧进程后再启动，或者重启电脑

**Comment by Tesla-AC** [comment]
default_encoding 换成 'utf-8' 之后可以正常使用了，print(proc.stdout) 也能够正常打印，最后一个修改 kill_process_at_start = no 我试了也可以正常使用，不过听你这么说好像会有副作用？所以没用最后这个办法。最后感谢解答 :)

**Comment by kjtsune** [comment]
Windows 系统的语言和编码有自己改过哪些设置吗，还是都默认？

**Comment by Tesla-AC** [comment]
编码应该只改过CMD的默认编码，因为运行一些控制台服务时输出的中文会乱码，所以改成了UTF-8

![image](https://github.com/kjtsune/embyToLocalPlayer/assets/56549504/de097f87-a52f-4c42-9a27-de368bc9398d)

**Comment by kjtsune** [comment]
目前已经强制使用 utf-8，不过如果会有额外不良反应，会再改回去。
