### ISSUE TITLE
[Feature Request] 视频标题能否从元数据中取

### ISSUE THREAD

**Issue by verygoodlee** [kjtsune/embyToLocalPlayer#19]
标题类似Emby这种，用户体验上来说要比原始文件名好很多
![1](https://github.com/kjtsune/embyToLocalPlayer/assets/45035465/f269f8d0-f3f9-4023-a5b3-610dc66c64c2)
我Fork了一份，简单对Emby实现了一下，只改了单文件的，没改播放列表，写的很随意就不PR了，只是测试一下可行性
verygoodlee/embyToLocalPlayer@07fc5f9
- 剧集
![2](https://github.com/kjtsune/embyToLocalPlayer/assets/45035465/e83d8c55-6f17-4032-86ef-40e7a96b1c6d)
- 电影
![3](https://github.com/kjtsune/embyToLocalPlayer/assets/45035465/0cca9322-0bad-44f1-b7d4-ad94a0ab8bc9)

感觉可以给个配置项，让用户选择展示元数据标题还是原始文件名

**Comment by kjtsune** [comment]
这样子多一个请求，起播会变慢。用油猴脚本获取可以降低影响。
有的播放器不支持设置标题。播放列表下一集是否支持设置标题。
标题可能用来和播放时间关联，回传记录。
是否有标题用来判断是不是读盘模式。
要测试不同服务端不同播放器不同播放模式。

这些是目前想到可能受到影响的部分，比较繁琐，等有空可能搞。

**Comment by kjtsune** [comment]
见 Pre-release

**Comment by verygoodlee** [comment]
> 见 Pre-release

mpv测试效果不错，单文件和播放列表都行
