### ISSUE TITLE
win11 22h2 重启失效

### ISSUE THREAD

**Issue by xbcui1975** [kjtsune/embyToLocalPlayer#2]
win11 22h2 加入启动组后重启失效 原来的win10没有任何问题 请大哥解决下

**Comment by kjtsune** [comment]
重启后用任务管理器查看是否有 python 进程，最好进入详细页面并打开命令行列。
若没有，.bat 里按3，进入启动文件夹，双击 .vbs 后再次查看。

**Comment by kjtsune** [comment]
22h2 22621.819 工作站版，经测试，没问题

**Comment by kjtsune** [comment]
任务管理器 > 启动，或者系统设置里搜索`启动应用`，检查启动项是否被禁用。

**Comment by xbcui1975** [comment]
已解决，谢谢
