### ISSUE TITLE
`--script-opts`建议改为`--script-opts-append`

### ISSUE THREAD

**Issue by verygoodlee** [kjtsune/embyToLocalPlayer#22]
最近的一个提交 kjtsune/embyToLocalPlayer@a1db326e8fded9e2fa13220da9b007fae3c93275
https://github.com/kjtsune/embyToLocalPlayer/blob/a1db326e8fded9e2fa13220da9b007fae3c93275/utils/players.py#L220
原因参考这里 https://github.com/hooke007/MPV_lazy/discussions/126#discussioncomment-7849058
`--script-opts`启动参数会把mpv.conf设置的`script-opts`完全覆盖，应该使用`--script-opts-append`在后面追加，
凡是[List Options](https://mpv.io/manual/stable/#list-options)都建议使用追加

**Comment by kjtsune** [comment]
修了
