### ISSUE TITLE
大佬能否出一期《播放列表（连续播放）支持》的教程呢？

### ISSUE THREAD

**Issue by SwePolice** [kjtsune/embyToLocalPlayer#25]
想要得到播放列表的支持，但是苦于不会操作，希望大佬能将加载播放列表的教程完善完善。多谢了

**Comment by kjtsune** [comment]
emby的播放列表功能尚不支持。
剧集的集播放列表已默认开启，无需配置，碰到问题按FAQ要求反馈。
