### ISSUE TITLE
win11 22h2 开脚本卡logo

### ISSUE THREAD

**Issue by xbcui1975** [kjtsune/embyToLocalPlayer#3]
![Snipaste_2023-01-28_15-01-48](https://user-images.githubusercontent.com/91305747/215252197-567b278c-068a-43e8-a32d-1f38b02106f1.png)
![Snipaste_2023-01-28_15-00-42](https://user-images.githubusercontent.com/91305747/215252202-21800271-1c8b-4670-81af-3e351c048095.png)

卡在logo界面进不去了

**Comment by kjtsune** [comment]
用浏览器新建用户的干净环境测试

**Comment by kjtsune** [comment]
与脚本无关。

禁用插件的前提下，在别人的vps 4.7.9 碰到，F12 查看，有的请求很久。原因未知。
需要等几分钟或更久就出来了。
可以换版本，给 Emby 加代理等测试。
建议反馈前先简单控制变量测试，及告诉对方尽量详细的信息。
