### ISSUE TITLE
脚本匹配 plex

### ISSUE THREAD

**Issue by raylanb** [kjtsune/embyToLocalPlayer#30]
添加以下内容即可：

```js
// @match        *://*.plex.tv/*
```

**Comment by kjtsune** [comment]
`// @match        https://app.plex.tv/*`
这样就行吧，还是会有其他情况？

**Comment by raylanb** [comment]
> `// @match https://app.plex.tv/*` 这样就行吧，还是会有其他情况？

这样也可以，我觉得你的匹配规则和上面那个相似，所以我就这么写了。你这样应该也没问题。
