### ISSUE TITLE
iina在使用磁盘模式后开启playlist功能同步观看进度失败

### ISSUE THREAD

**Issue by nostopp** [kjtsune/embyToLocalPlayer#32]
在使用磁盘模式并开启playlist后,iina在观看视频并关闭后未能成功同步进度,输出skip update progress: {key=} {_stop_sec=} not in playlist_data
目前来看emby中playlist_data 中的 key会是  "我心里危险的东西 S1:E14 - 病例.14「我们快变大人了」  |  我心里危险的东西 - S01E14 - 第14集-Nekomoe kissaten.mp4" 这种格式
而 mpv.command('get_property', 'media-title') 在iina情况下 返回值是 "我心里危险的东西 - S01E14 - 第14集-Nekomoe kissaten.mp4" 导致key未能命中而无法同步进度.

在playlist_add_mpv的循环中加了一段 
```
if getattr(mpv, 'is_iina'):
            playlist_data[basename] = ep
```
目前来看似乎是好了

**Comment by kjtsune** [comment]
感谢反馈，已更新zip
