### ISSUE TITLE
希望插件上可以切换播放器

### ISSUE THREAD

**Issue by raindrop213** [kjtsune/embyToLocalPlayer#33]
希望插件上可以切换播放器

需求：
有时不想开弹幕就不选弹弹play了，可以自由切换选mpv。

插件非常好用，希望可以变得更好，非常感谢！！

**Comment by kjtsune** [comment]
调用弹弹play的体验不怎么好，用的人也很少，暂不考虑在插件上切换。

两个解决方案：
1. 启用弹幕的片放指定路径
```
# 仅当服务端路径包含以下路径时使用弹弹播放，逗号隔开。全部文件都用弹弹播放就留空或删除。
enable_path = /disk/od/TV, /disk/e/anime
```
2. 自己写个脚本自动改 ini 文件中的总开关 yes no，放鼠标手势等快捷方式里。
