### ISSUE TITLE
弹弹play调用播放记录无法回传

### ISSUE THREAD

**Issue by Lain0v0** [kjtsune/embyToLocalPlayer#39]
Win11，emby，硬盘模式，1.1.13版本，弹弹play使用mpv弹幕外挂模式
因为想用自己的本地资源观看动漫，同时又想直接在mpv上看弹幕（比如芙莉莲早3周播放，只有巴哈有弹幕资源），所以尝试使用了以上组合方式。
emby调用弹弹play正常，弹弹play唤起mpv正常，调用的观看记录是弹弹play自己的观看记录；观看后关闭mpv窗口，mpv进度条会传到弹弹play的进度条里，关闭弹弹play后，播放进度不会回传到emby。
![image](https://github.com/kjtsune/embyToLocalPlayer/assets/53465954/fd3d23e2-51dc-494b-ac1e-cdb00f6c28e2)

另，或者请问是否有可能通过类似emby弹幕插件（danmaku.movie.kg）的方式，使用弹弹play的api，直接匹配相应弹幕，然后用MPV-Play-BiliBili-Comments插件的方法，将弹幕直接在mpv上显示呢？

**Comment by kjtsune** [comment]
弹弹play开启远程访问，若远程访问**曾经**启用过 Web验证，开启并填写 api密钥（不是用户名密码）
开始播放后10秒，日志会显示`dandan api started`

**Comment by kjtsune** [comment]
utils.python_mpv_jsonipc.MPVError: invalid parameter
用原版mpv测试，提供现在报错版本的mpv下载链接

**Comment by Lain0v0** [comment]
> 弹弹play开启远程访问，若远程访问**曾经**启用过 Web验证，开启并填写 api密钥（不是用户名密码） 开始播放后10秒，日志会显示`dandan api started`

感谢！原来开启远程后，需要再开启自动添加媒体库，或者手动先补充完dandanplay的媒体库信息。目前已经成功回传记录，效果非常好。mpv使用的是https://github.com/hooke007/MPV_lazy。
