### ISSUE TITLE
恒星播放器

### ISSUE THREAD

**Issue by VectorZhao** [kjtsune/embyToLocalPlayer#4]
目前windows上恒星播放器支持播放DV片源，不知道能否调用此播放器进行播放？
[https://www.stellarplayer.com/](https://www.stellarplayer.com/)

**Comment by kjtsune** [comment]
色彩转换 mpv 也可以，直通没有设备测试。
`vo = gpu-next`
网上别人配置有的还有一些其他选项，未测试。

以下为 mpv 0.35.1 色彩转换成 SDR，粗略测试，仅供参考：

Three Body 未知源 瓷
DV 版本: `【视频特性】...... Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU`
SDR 版本:  不知道文件里的 SDR 是自己转换还是原生的。
对比：DV 会比 SDR 颜色重一点。

WeCrashed ATV+
DV 版本: `HDR format...............: Dolby Vision, Version 1.0, dvhe.05.06, BL+RPU`
HDR 版本: `HDR format...............: SMPTE ST 2086, HDR10 compatible`
对比：没发现区别。
