### ISSUE TITLE
为啥`sub_lang_check`匹配语言而`subtitle_priority`匹配名称

### ISSUE THREAD

**Issue by verygoodlee** [kjtsune/embyToLocalPlayer#44]
看了下外挂字幕匹配相关的代码，感觉可以改成一样的规则，都用语言匹配比较好，mpv的`--slang`可以直接复制过来
- Emby 两者都是从MediaStreams里取字幕轨道，应该都包含语言信息吧
https://github.com/kjtsune/embyToLocalPlayer/blob/64254501c4440627610bf08a0c1c5f4036aade4b/utils/tools.py#L341-L345
https://github.com/kjtsune/embyToLocalPlayer/blob/64254501c4440627610bf08a0c1c5f4036aade4b/utils/net_tools.py#L487-L493
- Plex 同一个地方取得，更没啥问题
https://github.com/kjtsune/embyToLocalPlayer/blob/64254501c4440627610bf08a0c1c5f4036aade4b/utils/tools.py#L444-L455

是担心外挂字幕缺失语言信息吗，缺失的话语言按空字符串看，一个都匹配不上任选一个感觉也够用了，
目前subtitle_priority里ASS, SRT, Und对语言选择来说没啥帮助，也只是匹配不到预期语言时的兜底策略，跟匹配不上胡乱选一个没太大区别

**Comment by kjtsune** [comment]
`sub_lang_check` 忘记为什么用语言而不用标题了。
`subtitle_priority` 不采用语言是因为 emby 的数据里，语言都是 chi，无法区分简繁，我记得 mpv 不加 lua 也无法区分简繁。 ass 比 srt 优先也合理。可能还可以达到特效字幕优先的策略 （这个我忘记行不行了）

**Comment by verygoodlee** [comment]
旧版mpv只支持 ISO639-1的两字符zh 和ISO639-2的三字符chi，区分不了简繁，
但是最近更新支持了非常自由的IETF语言标记 mpv-player/mpv@5009e13，chs cht zh-Hans zh-Hant zh-CN zh-TW zh-HK 都没问题。

Emby的语言标记是区分简繁，而且外挂字幕可以识别后缀名前面的标记，chi chs cht 会被转换，
例如同一个字幕改三个不一样的名字 S01E01.chi.ass S01E01.chs.ass S01E01.cht.ass 
![image](https://github.com/kjtsune/embyToLocalPlayer/assets/45035465/925a8de3-89a1-4e2d-82b7-97c9606e01e8)
chi和chs转换成了zh-CN，cht转成了zh-TW，内封轨道还是还是保持原本的ISO639-2的三字符 jpn eng
![image](https://github.com/kjtsune/embyToLocalPlayer/assets/45035465/8005aa7a-3bff-4dcb-9d64-96fc52b5c078)

**Comment by verygoodlee** [comment]
不同标准的语言标记非常混乱，总结一下常见的中文标记：
- 简体：chs,zh-Hans,zh-CN
- 不区分简繁：chi,zh,cn
- 繁体：cht,zh-Hant,zh-TW,zh-HK
 另外早期还见过字幕组用 gb big5 区分简繁，不过这两个是字符集应该不属于语言标记范畴，近些年没咋看过用这个的了。

**Comment by kjtsune** [comment]
![image](https://github.com/kjtsune/embyToLocalPlayer/assets/110025665/3e2b87b7-d6b0-4a4b-a048-a6b0f7780214)
emby 内封字幕简繁都是 chi，外挂字幕有区分。用语言除了配置比较统一外还有其他什么优势吗？
* 鉴于 mpv 切换字幕时候会连视频流都重新加载，以后有考虑网页指定字幕时，也传给 mpv 字幕id，可能会受到影响。
传给 mpv 字幕id 的话，首页未选择字幕播放时，特效字幕优先也可以实现。
* 旧配置的老用户需要改配置。
* 大多数用户对语言标记不了解，用标题更所见即所得，兼容性和可配置性也高点。

**Comment by verygoodlee** [comment]
内封简繁都是chi因为封装的时候就给的chi，然后用嵌入式标题 `简体中文 | 繁體中文` `Chinese Simplified | Chinese Traditional` `CHS | CHT` 之类做区分，这样做的字幕组占多数，这确实是个问题
![image](https://github.com/kjtsune/embyToLocalPlayer/assets/45035465/b2f0b2af-c7e8-4bb8-a50a-7738b178eafd)
估计Emby会对chi做二次判断，有可能就是根据嵌入式标题来的，通过这两个综合判断出最终要展示的语言
![image](https://github.com/kjtsune/embyToLocalPlayer/assets/45035465/3ed5b62f-84d0-4f0c-94bf-5f03a28ab881)
对于这种封装的语言标记上已经区分了简繁的就没这种问题
![image](https://github.com/kjtsune/embyToLocalPlayer/assets/45035465/ffa6c9b2-1fbc-4a4c-97a5-c9fa393fbc69)


用标题匹配确实对普通用户更友好，都改成标题匹配也行，目前的一个语言一个标题太乱了

**Comment by kjtsune** [comment]
想起来了，sub_lang_check 当初是为了避免一种情况才用语言而不是标题。
名为 filelist 的 pt 站，含中文内封字幕的视频还会加一个罗马尼亚的外挂字幕。
如果用标题判断且配置的规则有 ass und 等兜底规则，很有可能自动选了外挂字幕。
不过问题不大，这种情况有其他解决方案了。

**Comment by kjtsune** [comment]
统一外挂字幕选择优先配置。`[dev] > sub_lang_check` 与 `[playlist] > subtitle_priority `弃用。  
新配置：`[dev] > subtitle_priority` 。首次运行时会自动覆写更新配置文件相关部分。

我很少外挂字幕文件，如果碰到问题再修。

**Comment by verygoodlee** [comment]
启动什么都没做，cpu持续占用异常，跑一段时间风扇都开始猛转了，可能有啥死循环
![屏幕截图 2024-05-17 234833](https://github.com/kjtsune/embyToLocalPlayer/assets/45035465/761bf7f0-c1b0-445c-9774-835679a0aad9)
日志输出很干净，看不出啥
![image](https://github.com/kjtsune/embyToLocalPlayer/assets/45035465/115fba75-78f5-449a-8ed7-37f0ccd257f6)

**Comment by verygoodlee** [comment]
当不选字幕时，直接忽略内封从外挂里匹配是吗，这个用用例会选中最后一个外挂是正常的吧
![image](https://github.com/kjtsune/embyToLocalPlayer/assets/45035465/5c477bc0-af4b-41e4-8e39-58076f2b7414)
省去了旧版先检查内封有没有中文，确实没必要检查，搞复杂了也没啥优势，
一般来说有配外挂字幕的，都会配个比内封更优秀的字幕。

**Comment by kjtsune** [comment]
cpu 占用问题修了。

是的，基本上外挂会比内封好。
