### ISSUE TITLE
更新了过后批处理文件要不使用管理员权限打开，但是我的windows默认打开都是管理员

### ISSUE THREAD

**Issue by XXZM260** [kjtsune/embyToLocalPlayer#46]

**Comment by kjtsune** [comment]
你的 Windows 用户名是什么

**Comment by XXZM260** [comment]
> 你的 Windows 用户名是什么

不是默认的administrator

**Comment by kjtsune** [comment]
你的用户名是什么，我也是管理员账户，没提权运行是可以正常启动的。

**Comment by kjtsune** [comment]
把这段删了就可以。https://github.com/kjtsune/embyToLocalPlayer/blob/f5ad9143cf0993ba97c5be80b976b509646a372e/embyToLocalPlayer_debug.bat#L6-L11
