### ISSUE TITLE
最新版本一启动cpu占用严重，播放器可不可以新增支持powerDVD？

### ISSUE THREAD

**Issue by changanning** [kjtsune/embyToLocalPlayer#47]

**Comment by kjtsune** [comment]
cpu占用修了。bat 按6。

powerDVD 这种没什么好办法获取播放时间与控制播放列表。
理论上可以播放，只是不会回传，你可以填进去试试看

**Comment by changanning** [comment]
不需要回传和播放列表，很奇怪的是，设置启动路径为PowerDVD的启动路径后，PowerDVD启动l，但是没有接收到任何信息

**Comment by changanning** [comment]
好奇怪，从这里下的[emby](https://github.com/MediaBrowser/Emby.Releases/tree/4.8.7.0)PowerDVD就不能打开，而且使用pot和mpv也不能打开iso原盘文件。用我原先从不知道下的4.7版本（但是服务器还是最新的4.8.6版本）就可以启动PowerDVD

**Comment by kjtsune** [comment]
PowerDVD 不能虚拟机运行，无法测试。自行参考其他播放器的命令行日志测试。
非读盘模式，pot 和 mpv 都可以观察到在下载 iso。但无法播放。
smb 挂载读盘模式，pot 230208 和 mpv.net 6.0.3.1 正常播放。

**Comment by kjtsune** [comment]
[dev] > player_by_path | force_disk_mode_path
这两个配置可能对想播放iso的其他用户有帮助。
