### ISSUE TITLE
请教字幕问题，连续播放字幕发生错误

### ISSUE THREAD

**Issue by wjw054509** [kjtsune/embyToLocalPlayer#52]
FAQ提到这个“视频文件的内置字幕当作外挂字幕处理会导致播放器语言设置失效。（外挂字幕最优先）”，没懂啥意思。
我在使用eMBY播放后，第一集播放完毕自动播放列表内第二个文件时候字幕就发生加载错误，视频中会同时显示第一集和第二集的字幕，如何解决啊，

**Comment by kjtsune** [comment]
faq 如何反馈
