### ISSUE TITLE
无法在Mac上开机自运行

### ISSUE THREAD

**Issue by keeper-0** [kjtsune/embyToLocalPlayer#6]
使用MAC13.3系统 iina播放器，jellyfin服务端。
根据自动运行教程，卡在“启动台 > 自动操作 > 文件 > 新建 > 应用程序 > 运行 Shell 脚本 >把 emby_script_run.command 文件拖入 > 点击运行后测试播放”这里，这里测试 iina 会显示“无法打开文件或流！”。
而直接双击运行emby_script_run.command文件，是可以正常调用iina播放器的，求大大指导
![上传截屏2023-05-17 11.20.44.png...]()

**Comment by keeper-0** [comment]
这是运行正常开机的情况

Last login: Wed May 17 11:12:25 on ttys000
/Users/wuti/文档/embyToLocalPlayer/emby_script_run.command ; exit;
wuti@wuti ~ % /Users/wuti/文档/embyToLocalPlayer/emby_script_run.command ; exit;
run in /Users/wuti/文档/embyToLocalPlayer
05/17/23 11:28 ['Python path: /Library/Developer/CommandLineTools/usr/bin/python3']
05/17/23 11:28 ['ini path: /Users/_hide_user_/文档/embyToLocalPlayer/embyToLocalPlayer_config.ini']
05/17/23 11:28 macOS-13.3-x86_64-i386-64bit Python-3.9.6
05/17/23 11:28 /Users/_hide_user_/文档/embyToLocalPlayer/embyToLocalPlayer.py
05/17/23 11:28 serving at 127.0.0.1:58000

**Comment by kjtsune** [comment]
把 emby_script_run.command 文件里的内容复制到 运行 Shell 脚本 的框里试试看

**Comment by keeper-0** [comment]
如果直接复制的话，运行会出现问题，提示在用户目录下没有embyToLocalPlayer.py这个文件，将所有文件放在用户目录下之后，可以运行，但是结果同样显示“无法打开文件或流！”
<img width="813" alt="截屏2023-05-29 23 12 37" src="https://github.com/kjtsune/embyToLocalPlayer/assets/93301915/6b89c067-52b8-44ea-b232-5b870c9195cb">
<img width="1896" alt="截屏2023-05-29 23 12 25" src="https://github.com/kjtsune/embyToLocalPlayer/assets/93301915/01e8c9e8-35eb-4764-a6c1-19952c9c7601">
<img width="265" alt="截屏2023-05-29 23 11 57" src="https://github.com/kjtsune/embyToLocalPlayer/assets/93301915/918e774e-32b7-4edd-b62e-fb5d82454ab2">
<img width="981" alt="截屏2023-05-29 23 11 44" src="https://github.com/kjtsune/embyToLocalPlayer/assets/93301915/0b6c09ff-5fd4-4921-b427-8ee4491daf1b">

**Comment by kjtsune** [comment]
换mpv或者vlc试试看。如果文件在本地，还可以切换成读盘模式看看。

**Comment by Taosky** [comment]
Launchctl也不行，好像需要在正常的用户命令环境下执行才行。

**曲线救国：**

命令后面加上& 然后等待几秒退出（我用的iTerm2退出太快会提示）
<img width="299" alt="图片" src="https://github.com/kjtsune/embyToLocalPlayer/assets/7688350/b92022d0-871f-4b4e-af01-93d689f3d9e7">

**Comment by kjtsune** [comment]
本回复的情况与楼主不一致，仅供参考

有位 Monterey 12.6.6 的用户，反应启动后状态栏会有齿轮。解决方案如下：
把文件拖入的操作替换成写以下内容，注意更改cd目录为你保存的目录。
cd ~/App/embyToLocalPlayer && nohup ./emby_script_run.command > run.log 2&>1 &

**Comment by Eatsolx** [comment]
我也存在此问题

**Comment by Eatsolx** [comment]
修正，如果用screen挂后台无需使用AppleScript，可直接Run Shell Script

**Comment by Eatsolx** [comment]
这个issue可以关闭了吧

**Comment by kjtsune** [comment]
最好不同版本的系统都测试下，不过短时间内我没环境，先关闭，有问题再提。
