### ISSUE TITLE
jellyfin播放失败，网页点击播放后，py脚本无新增日志。

### ISSUE THREAD

**Issue by X012C** [kjtsune/embyToLocalPlayer#62]
播放失败：
![image](https://github.com/user-attachments/assets/c2cc1ef9-f1f3-4700-a905-3438bbb48f1b)
路径：
![image](https://github.com/user-attachments/assets/9522acd5-2fe8-42a7-b546-036c8c04a2d3)
debug运行结果：
![image](https://github.com/user-attachments/assets/06591fa8-43e3-45cd-9f52-af522583e830)

**Comment by kjtsune** [comment]
提供在 jellyfin 页面点击浏览器油猴插件图标后的截图。

**Comment by X012C** [comment]
> 提供在 jellyfin 页面点击浏览器油猴插件图标后的截图。
![image](https://github.com/user-attachments/assets/a852a845-95e4-4d2b-8901-3600295c06c0)
![image](https://github.com/user-attachments/assets/5e609cf8-2fa7-4a58-8f1d-5744bf590e41)

**Comment by kjtsune** [comment]
10.9.2和10.9.8均测试正常。换个浏览器或者重装油猴脚本试一下。
也可以浏览器F12看控制台有没有什么异常，正常点击后会有蓝色的日志打印。

**Comment by X012C** [comment]
> 10.9.2和10.9.8均测试正常。换个浏览器或者重装油猴脚本试一下。 也可以浏览器F12看控制台有没有什么异常，正常点击后会有蓝色的日志打印。

F12有两个bug，不过我看不懂。图中红框如果是想要引用的是jellyfin地址，那问题可能就是在这里。
![image](https://github.com/user-attachments/assets/a6628964-9d54-49e4-9c71-6a1fbc1eb778)

**Comment by kjtsune** [comment]
油猴脚本也没问题，已经获得所需数据。问题出在油猴脚本没成功通过网络把数据发给py脚本。
1. 可能被浏览器插件拦截：  
    1. 油猴插件，编辑脚本，设置，XHR 安全，把127.0.0.1加入白名单。
    2. 重装油猴脚本。
    3. 换浏览器。
2. py脚本没成功监听58000端口。  
    1. 任务管理器结束所有python进程。
    2. 资源管理器检查侦听端口是否被别的程序占用。
    3. bat按1后，资源管理器检查侦听端口58000是否正常被python监听。

**Comment by X012C** [comment]
> 油猴脚本也没问题，已经获得所需数据。问题出在油猴脚本没成功通过网络把数据发给py脚本。
> 
> 1. 可能被浏览器插件拦截：
>    
>    1. 油猴插件，编辑脚本，设置，XHR 安全，把127.0.0.1加入白名单。
>    2. 重装油猴脚本。
>    3. 换浏览器。
> 2. py脚本没成功监听58000端口。
>    
>    1. 任务管理器结束所有python进程。
>    2. 资源管理器检查侦听端口是否被别的程序占用。
>    3. bat按1后，资源管理器检查侦听端口58000是否正常被python监听。

重装好几遍了，白名单那个好像是默认就在里面的。这次F12还有个提示CSS格式提示，我也没看懂，提示链接也是和jellyfin地址关联的。
![image](https://github.com/user-attachments/assets/473d1fcd-f521-4b69-9a38-d2f9b3fbaa27)
如果上述截图提示和问题无关，就这样了吧。

**Comment by kjtsune** [comment]
无关，油猴已经获得所需数据

**Comment by kjtsune** [comment]
也可以试一下这两个
[Tampermonkey v2](https://chromewebstore.google.com/detail/lcmhijbkigalmkeommnijlpobloojgfn)
[Violentmonkey](https://chrome.google.com/webstore/detail/violent-monkey/jinjaccalgkegednnccohejagnlnfdag)
