### ISSUE TITLE
jellyfin web打开需要选择服务器，点击连接后失败，关闭插件后正常

### ISSUE THREAD

**Issue by Edmondguo** [kjtsune/embyToLocalPlayer#63]
如图是F12的信息，关闭插件后正常，jellyfin版本 中国特供版的10.8.13
![image](https://github.com/user-attachments/assets/32ead63a-c5dd-4e33-a7d6-e0ff4d203892)

**Comment by kjtsune** [comment]
`选择服务器`这个页面要怎么触发，都是直接跳登录窗口了

**Comment by Edmondguo** [comment]
> `选择服务器`这个页面要怎么触发，都是直接跳登录窗口了

正常使用的情况下我也不知道怎么触发进入这个界面。。之前插件开启也是正常的，不知道哪天忽然变成这样了。浏览器有cookie记录了账户密码。只要关掉插件，就是直接进去到正常的jellyfin剧集电影的画面。打开插件就会跳转到这个界面。

**Comment by kjtsune** [comment]
把这个页面的网址发我看一下。
可以尝试删除油猴脚本重装，或者删除浏览器cookie缓存等试试看。
