### ISSUE TITLE
Miss  duration in plex media tv show！

### ISSUE THREAD

**Issue by zhengsun2020** [kjtsune/embyToLocalPlayer#64]
when i saw tv show ，i got this info from cmd out：

 File "D:\Downloads\embyToLocalPlayer-python-embed-win32\utils\http_server.py", line 65, in do_POST
    data = parse_received_data_emby(data) if self.path.startswith('/emby') else parse_received_data_plex(data)
  File "D:\Downloads\embyToLocalPlayer-python-embed-win32\utils\tools.py", line 489, in parse_received_data_plex
    duration = data['duration']
KeyError: 'duration'

i print data from Plex and tv show send info json includ “duration” in selected season espoid
'Media': [{
		'id': 586519,
		'duration': 1445162,
		'bitrate': 3018,
		'width': 1920,
		'height': 1080,
		
but no in next espoid
'Media': [{
		'id': 586520,
		'Part': [{
			'id': 608139,
			'key': '/library/parts/608139/1722653858/file.mkv',
			'file': 'D:\\XXXXXXX',
			'size': 435248006
		}]
so the program process  this json can not get duration, and "KeyError: 'duration'" here

And the last year tv shows added in my lib , PLEX would send all duration of every espoid! 

Finallly I modified these  line in tools.py , it work fine:

        duration = data.get('duration')

        if data['Part'][0].get('Stream'):
            sub_dict_list = [i for i in data['Part'][0]['Stream'] if i.get('streamType') == 3 and i.get('key')]

**Comment by kjtsune** [comment]
docker pull linuxserver/plex
版本1.40.4.8679
最新版无法复现，什么服务端版本，注意不是 webui 版本。

**Comment by zhengsun2020** [comment]
版本1.40.4.8679
服务器 VPS海外 和 国内的Windows都能复现，我已经修改我自己的代码了。主要是 获得服务器传回的jason 很奇怪 电视剧有些集没有时长信息等详细信息，看过一次会有，因为脚本要读取所有集信息，有的就是没有。不知道是否和plex的TV刮削出问题有关系。

注释了  #duration = data['duration']
并做了如下两处修改
        if data['Part'][0].get('Stream') is not None:
            sub_dict_list = [i for i in data['Part'][0]['Stream'] if i.get('streamType') == 3 and i.get('key')]
        else:
            sub_dict_list = []

        if duration is not None:  
            total_sec = int(duration) // (10 ** 3)  
        else:  
            duration = "60000000"
            total_sec = 60000  # 或者其他合适的默认值
        position = start_sec / total_sec

**Comment by kjtsune** [comment]
新入库的电视项目，没点开详情或者播放过的，浏览器进入下一集详情会看不到字幕视频流等数据，同时也会无法快速播放。体现在本地服浏览器播放，点下一集无法秒播，要转很久。用本项目调用播放的话，下一集会卡住。等plex自己修了。

**Comment by zhengsun2020** [comment]
我怀疑他们就打算这么做下去了，我的1.40 还降级不了 1.32

**Comment by zhengsun2020** [comment]
> 新入库的电视项目，没点开详情或者播放过的，浏览器进入下一集详情会看不到字幕视频流等数据，同时也会无法快速播放。体现在本地服浏览器播放，点下一集无法秒播，要转很久。用本项目调用播放的话，下一集会卡住。等plex自己修了。

而且刮削的剧情介绍也没有，必须手工刷新元数据

**Comment by kjtsune** [comment]
> 是的 就是因为他不传送下一集的各种信息，而咱们的脚本 有的地方不是 get方法，是直接引用，这里就报错了，我就把这几个地方增加了判断。

不止不传送，而是没有去获取，不然就不会播放下一集卡住了。
这几个数据都有作用，目前不考虑适配，建议降级服务端。

对于想使用的用户，可以自行修改以下几个变量的值，外挂字幕和部分功能可能会失效。
https://github.com/kjtsune/embyToLocalPlayer/blob/7be8a192484af4f4e078332126959addde1d018e/utils/tools.py#L489
`        duration = data.get('duration', 10**12)`

https://github.com/kjtsune/embyToLocalPlayer/blob/7be8a192484af4f4e078332126959addde1d018e/utils/tools.py#L494
`        sub_dict_list = []`

https://github.com/kjtsune/embyToLocalPlayer/blob/7be8a192484af4f4e078332126959addde1d018e/utils/tools.py#L522
`        total_sec = duration // (10 ** 3)`

**Comment by zhengsun2020** [comment]
> > 是的 就是因为他不传送下一集的各种信息，而咱们的脚本 有的地方不是 get方法，是直接引用，这里就报错了，我就把这几个地方增加了判断。
> 
> 不止不传送，而是没有去获取，不然就不会播放下一集卡住了。 这几个数据都有作用，目前不考虑适配，建议降级服务端。
> 
> 对于想使用的用户，可以自行修改以下几个变量的值，外挂字幕和部分功能可能会失效。
> 
> https://github.com/kjtsune/embyToLocalPlayer/blob/7be8a192484af4f4e078332126959addde1d018e/utils/tools.py#L489
> 
> 
> ` duration = data.get('duration', 10**12)`
> https://github.com/kjtsune/embyToLocalPlayer/blob/7be8a192484af4f4e078332126959addde1d018e/utils/tools.py#L494
> 
> 
> ` sub_dict_list = []`
> https://github.com/kjtsune/embyToLocalPlayer/blob/7be8a192484af4f4e078332126959addde1d018e/utils/tools.py#L522
> 
> 
> ` total_sec = duration // (10 ** 3)`

降级我试过 告诉我系统DB失败启动不了

**Comment by kjtsune** [comment]
那就先这样子用吧。
本地挂载用户可以启用读盘模式来解决外挂字幕问题。

**Comment by zhengsun2020** [comment]
请问一下读盘模式是啥，我从来没开过，我看的都是GD网盘的资源。可能外挂字幕也少

**Comment by zhengsun2020** [comment]
明白了，我测试了读盘模式可以，那我平常一直开着读盘模式可以吗？有什么缺点？

**Comment by kjtsune** [comment]
https://github.com/kjtsune/embyToLocalPlayer/blob/7be8a192484af4f4e078332126959addde1d018e/README.md#L116-L119

**Comment by kjtsune** [comment]
> 明白了，我测试了读盘模式可以，那我平常一直开着读盘模式可以吗？有什么缺点？

可以，缺点不知道。

**Comment by zhengsun2020** [comment]
我看日志明白了，本地模式必须服务器和文件以及播放是在本地才行，如果是远端服务器开着本地模式，这时本地没有实际文件那就是报错

**Comment by kjtsune** [comment]
> 我看日志明白了，本地模式必须服务器和文件以及播放是在本地才行，如果是远端服务器开着本地模式，这时本地没有实际文件那就是报错

远端服务器也可以，本地挂载GD就可以。看 ini 配置文件。

**Comment by kjtsune** [comment]
> 这个1.40改动太大了，而且我测试了 无法回退1.32.8 简直无语了 ，最近刮削也完蛋

跨大版本回退一般需要重建。刮削是因为被墙了。

**Comment by zhengsun2020** [comment]
重建就算了，而且我发现 现在的plex 外置srt 出不来是因为 download=0不起作用，他还是会按照下载处理，所以potplayer就无法支持srt，Emby就是直接可以访问的方式打开srt。
这个我调试了半天也不行只能本地硬盘模式就能解决，但是得自己想着点切换，因为有的时候需要连接朋友的plex就不能用本地硬盘模式了。

**Comment by kjtsune** [comment]
> 只能本地硬盘模式就能解决，但是得自己想着点切换

\# 当服务端路径包含以下前缀强制使用读盘模式，忽略油猴设置。逗号隔开，例如: /disk/p, disk/e
force_disk_mode_path =
临时曲线救国方案。

**Comment by kjtsune** [comment]
> plex 外置srt 出不来是因为 download=0不起作用

mpv 没这问题，pot 原因未知。
随便修了 plex 选中字幕时的bug。

**Comment by kjtsune** [comment]
https://192-168-123-123.abcdefg.plex.direct:32400/library/streams/13350?download=0&X-Plex-Token=_hide_api_key_

可以用局域网ip 192.168.... 访问plex播放试试看。
我测试也是直接浏览器中显示srt的内容，但链接格式和你有点区别。这种是他自己转换的。

**Comment by zhengsun2020** [comment]
是的我就是这么测试的，我的1.40.4.8679服务端（Windows、linux）都有这个问题，就是一输入url这种（URL换成了局域网IP）然后就是下载过来了，而不是显示在浏览器中

**Comment by kjtsune** [comment]
那就不懂了，我也是这个版本。版本1.40.4.8679

**Comment by zhengsun2020** [comment]
我再找找服务设置问题吧

**Comment by kjtsune** [comment]
当然，只是会在浏览器里显示而已，我的pot也是无法加载字幕的。mpv可以。

**Comment by zhengsun2020** [comment]
外置srt 您那里也不行是吧，那就不一定是和这个有关。那就算了 我用mpv也可

**Comment by zhengsun2020** [comment]
本地模式是因为他自己去取 同名的srt 可以显示。直接指定反而就不行

**Comment by zhengsun2020** [comment]
def pot_player_start(cmd: list, start_sec=None, sub_file=None, media_title=None, get_stop_sec=True, **_):
    # 确保每个参数都被正确的引号包裹
    def wrap_quotes(arg):
        return f'"{arg}"' if ' ' in arg or '://' in arg else arg
    if cmd:
        # 包裹第一个参数（程序路径）
        cmd[0] = wrap_quotes(cmd[0])
        
        # 包裹第二个参数（视频 URL）
        if len(cmd) > 1:
            cmd[1] = wrap_quotes(cmd[1])

    if sub_file:
        if 'Plex-Token' in sub_file:
            sub_file = save_sub_file(sub_file)
        cmd.append(f'/sub="{sub_file}"')
    if start_sec is not None:
        format_time = time.strftime('%H:%M:%S', time.gmtime(int(start_sec)))
        cmd += [f'/seek={format_time}']
    if media_title:
        cmd += [f'/title="{media_title}"']
    if pot_conf := configs.raw.get('dev', 'pot_conf', fallback=''):
        cmd += [f'config={pot_conf.strip()}']

    logger.info(cmd)
    # 将 cmd 列表拼接为单个字符串
    full_cmd = ' '.join(cmd)
    logger.info(full_cmd)
    
    # 使用 shell=True 执行命令字符串
    player = subprocess.Popen(full_cmd, shell=True)
    #player = subprocess.Popen(cmd)
    
    activate_window_by_pid(player.pid, sleep=1)
    if not get_stop_sec:
        return

    return dict(pid=player.pid, player_path=cmd[0])
    
    
    修改好了，用本地cmd模式启动potplayer

**Comment by zhengsun2020** [comment]
但是这么做就不能回传观看位置了。。。

**Comment by zhengsun2020** [comment]
而且我记得原来在播放列表中可以增加同系列的 集 ，怎么现在不行了？

**Comment by kjtsune** [comment]
我就是本地文件的，没有网盘，也是会缺失数据。
不过这次又测试，跳下一集播放不会卡住了。

简单更新了下。也给用户提示会有字幕等问题。

**Comment by zhengsun2020** [comment]
只要读过一次文件就OK了，我是本地的 strm文件改名为 mkv 然后扫库，实际没有媒体数据，然后再挂在网盘的媒体文件。所以第一次播放的时候后面的集和当前集都没有媒体数据。程序如果不判断直接取就会异常。所以我改了几个地方就是适应这种情况

**Comment by kjtsune** [comment]
https://github.com/kjtsune/embyToLocalPlayer/commit/01b188d58531a30c96a788e8d6dc6f5951435e66
