### ISSUE TITLE
打开bat文件显示错误

### ISSUE THREAD

**Issue by kitaki-Ciallo** [kjtsune/embyToLocalPlayer#65]
双击打开bat后显示

ERROR: do not run as admin!
ERROR: do not run as admin!
all tasks are finished.
Press any key to continue . . .

但我并没有使用管理者权限打开，求解决

**Comment by kjtsune** [comment]
微软邮箱账户还是本地账户

**Comment by kitaki-Ciallo** [comment]
> 微软邮箱账户还是本地账户

邮箱账户

**Comment by kjtsune** [comment]
把这几行删掉就可以。
https://github.com/kjtsune/embyToLocalPlayer/blob/7be8a192484af4f4e078332126959addde1d018e/utils/others/embyToLocalPlayer_debug.bat#L6-L11

**Comment by kitaki-Ciallo** [comment]
已解决，感谢！
