### ISSUE TITLE
错误提示“player_is_running, skip. You may want to disable one_instance_mode, see detail in config file”，其实播放器并未运行

### ISSUE THREAD

**Issue by yeezylife** [kjtsune/embyToLocalPlayer#67]
首先我发现有的时候，在使用脚本的状态下，打不开影片，明明是很空闲的时段，不应该这样。。（点播放闪过提示，可是播放器一直不出来）

这种时候，我尝试关闭脚本用网页播放，就可以很流畅的播放出来，我就想是不是脚本有什么问题

在这一次播放失败的时候，控制台里发现这个“player_is_running, skip. You may want to disable one_instance_mode, see detail in config file”

但是我仔细检查了进程，我指定的播放器mpv并没有运行呀。。。如下图，按名称排列。播放器真的没有运行，控制台里却说播放器正在运行，停止播放。我想这应该是空闲时段用脚本播不出来，用网页却可以播出来的原因吧。。

![clipboard](https://github.com/user-attachments/assets/13ea6736-c669-435d-a3bd-5e6bbc14da06)

**Comment by kjtsune** [comment]
这是单实例模式在脚本产生预期外错误时的表现。
像你这个就是，访问被服务器禁止了，你可以问一下服主是不是不给用这个脚本调用播放。
解决方案如脚本提示：You may want to disable one_instance_mode, see detail in config file.
但回传失败的问题没解决，如果只是服主禁国内访问，可以尝试加代理。

**Comment by kjtsune** [comment]
偶尔的话，也可能单纯网络问题，还是加代理或者禁用单实例模式

**Comment by kjtsune** [comment]
这是单实例模式在脚本产生预期外错误时的表现。故意的
