### ISSUE TITLE
某些日文目录下的视频无法使用硬盘读取模式播放

### ISSUE THREAD

**Issue by chrisguan7777** [kjtsune/embyToLocalPlayer#74]
最近遇到这个问题，不知道是emby对日文处理的问题还是什么，看起来完全相同的日文，但是实际编码是不一样的

建议在tools.py的def get_player_cmd(media_path, file_path): 方法里面，对media_path进行处理一下，
实测加入一下代码可以解决问题
media_path = unicodedata.normalize('NFC', media_path)

**Comment by kjtsune** [comment]
感谢反馈，先更新zip文件了。
https://github.com/kjtsune/embyToLocalPlayer/blob/3e0ef911abc17d4d7564337c95f10e404afdbd71/utils/tools.py#L195
`    return file_path if file_path.startswith('http') else unicodedata.normalize('NFC', file_path)`
