### ISSUE TITLE
显示不同播放器按钮

### ISSUE THREAD

**Issue by SHL-COOL** [kjtsune/embyToLocalPlayer#75]
是否可以支持在页面上显示某些播放器的按钮，这样可以根据不同的电影选择不同的播放器播放
比如下面的这个效果
![image](https://github.com/user-attachments/assets/0f480766-7ebc-42c5-879e-4a102e3f7f91)

**Comment by SHL-COOL** [comment]
发现配置里面有个根据关键字 自动选择播放器的配置，也能实现我的需求

**Comment by haildceu1** [comment]
请问一下这个根据关键字在哪里

> 发现配置里面有个根据关键字 自动选择播放器的配置，也能实现我的需求
