### ISSUE TITLE
实时回传不支持多个播放器实例吗

### ISSUE THREAD

**Issue by verygoodlee** [kjtsune/embyToLocalPlayer#78]
已有一个实例在回传进度的情况下启动另一个实例，第二个开始回传第一个就会失效，两个没法同时回传

**Comment by kjtsune** [comment]
https://github.com/kjtsune/embyToLocalPlayer/blob/0cf4d86ef63405f76ec67d121713850ccf700948/utils/players.py#L80

https://github.com/kjtsune/embyToLocalPlayer/blob/0cf4d86ef63405f76ec67d121713850ccf700948/utils/players.py#L275-L277

是的，不过按理应该是有一个播放器实例关闭后，当前所有实时回传会关闭。

**Comment by kjtsune** [comment]
禁用脚本，浏览器在不同窗口直接播放，Emby 后台的实时回传卡片是在两个实例间反复横跳。

**Comment by kjtsune** [comment]
经测试，设备ID不同时，会同时展示。
https://github.com/kjtsune/embyToLocalPlayer/blob/0cf4d86ef63405f76ec67d121713850ccf700948/utils/net_tools.py#L255

**Comment by kjtsune** [comment]
估计现有方案是不会影响Emby统计数据的，因为官方浏览器客户端也是这种行为。
实际用处也不大，保持与官方一致比较好。
