### ISSUE TITLE
大佬你好，选项2后台运行不起作用

### ISSUE THREAD

**Issue by sadfdasfd** [kjtsune/embyToLocalPlayer#80]
按选项1run in console是可以正常运作的，按了2之后就无法调用播放器了，LOG.TXT中也只有之前run in console状态下的记录。
重启电脑可以看到开机自启是没问题的，运行框闪了一下之后自己关掉了，但是没办法调用播放器，LOG.TXT中也没有任何显示。
![屏幕截图 2024-10-21 180646](https://github.com/user-attachments/assets/31ec733a-4b15-4038-900f-06f305832e40)

**Comment by kjtsune** [comment]
试一下 AutoHotkey 自启动解决方案：
* 下载 [etlp_ahk.zip](https://github.com/user-attachments/files/17483792/etlp_ahk.zip) 解压到 `embyToLocalPlayer.py` 所在目录。
* 运行 `embyToLocalPlayer.exe` 来代替使用 `_debug.bat`
* 或者 自行安装 [ahk v2](https://www.autohotkey.com/) ，然后运行 `embyToLocalPlayer.ahk` 来代替使用 `_debug.bat`

**Comment by kjtsune** [comment]
> 自启是没问题的，运行框闪了一下之后自己关掉了

这个是不正常的，正常是不会闪框。

> 自己关掉了

闪框还自己关掉，可能是自己把自己结束进程了。
可以改 ini 文件，`kill_process_at_start = no` 试试看。副作用看注释。

**Comment by sadfdasfd** [comment]
感谢大佬的热心帮助，尝试了很多办法都不起作用，可能是我的电脑什么地方设置有问题吧
