### ISSUE TITLE
KikoPlay 播放列表

### ISSUE THREAD

**Issue by thcehocai** [kjtsune/embyToLocalPlayer#83]
使用其他播放器不支持加载播放列表吗 我使用的是kikoplay 它也是用libmpv内核写的

**Comment by kjtsune** [comment]
> KikoPlay的播放列表是一个复杂的树形列表，不会和libmpv内部的列表同步（比较麻烦，会多很多不必要的操作），也不希望通过外部控制libmpv的方式来控制列表

https://github.com/KikoPlayProject/KikoPlay/issues/168

**Comment by kjtsune** [comment]
https://github.com/Kosette/danmaku

[mpv](https://mpv.io/) 通过 [dandanplay API](https://api.dandanplay.net/swagger/ui/index) 驱动的弹幕插件。插件会将当前播放文件的名称和哈希值发送到 dandanplay 服务器，获取匹配的弹幕评论，可以和 Emby 搭配使用。
