### ISSUE TITLE
potplayer 显示 “服务器已关闭，无法播放”

### ISSUE THREAD

**Issue by fanglangxinghai** [kjtsune/embyToLocalPlayer#84]
jellyfin用的是现在windows的最新版本10.10.1，potplayer也是更新到最新版本。

开启油猴脚本，播放后，potplayer软件开启，然后显示“服务器已关闭，无法播放”。

![2024-11-07 16_10_45-Window](https://github.com/user-attachments/assets/d123ad2a-e739-4cb6-9393-499516943cbd)

关闭油猴脚本，可以在jellyfin中播放。

**Comment by kjtsune** [comment]
看 FAQ

**Comment by kjtsune** [comment]
https://github.com/kjtsune/embyToLocalPlayer?tab=readme-ov-file#播放器相关
