### ISSUE TITLE
无法唤醒播放软件，日志提示KeyError: 'Chapters'

### ISSUE THREAD

**Issue by pandalaohe** [kjtsune/embyToLocalPlayer#85]
媒体服务器： EMBY 版本 [4.9.0.30]测试版
本地播放器： Potplayer241015(1.7.22347) x64
油猴插件： 2024.04.11（EMBY最新），开启读取硬盘模式
本地配置： 播放器选择 pot，其他默认

问题描述：
emby网页端点击播放后无法弹出potplayer

![image](https://github.com/user-attachments/assets/edc28f02-8d24-42fc-bf8d-f7771493c864)

**Comment by kjtsune** [comment]
https://github.com/kjtsune/embyToLocalPlayer/releases/tag/2024.10.30
