### ISSUE TITLE
自动启动时提示"系统找不到指定的文件"

### ISSUE THREAD

**Issue by pandalaohe** [kjtsune/embyToLocalPlayer#86]
媒体服务器： EMBY 版本 [4.9.0.30]测试版
本地播放器： Potplayer241015(1.7.22347) x64
油猴插件： 2024.04.11（EMBY最新），开启读取硬盘模式
本地配置： 播放器选择 pot，其他默认

问题描述：
加入系统自启动,提示找80070002错误 "系统找不到指定的文件"

![image](https://github.com/user-attachments/assets/dac5cbd1-6956-46ee-98ce-309df76f7e08)

**Comment by kjtsune** [comment]
看问题排查

**Comment by kjtsune** [comment]
1. 创建的VBS脚本不是ANSI编码导致无法处理含中文的路径
2. https://github.com/kjtsune/embyToLocalPlayer/issues/14#issuecomment-2430602205
