### ISSUE TITLE
mkv、mp4可以回传，但原盘格式、iso格式的电影不支持回传进度

### ISSUE THREAD

**Issue by frvery** [kjtsune/embyToLocalPlayer#88]
求解答，自己测试了下，安卓客户端yamby可以实现看原盘电影回传进度

**Comment by kjtsune** [comment]
提供iso文件播放到一半可以回传的截图。及对应iso种子名称。

**Comment by frvery** [comment]
> 提供iso文件播放到一半可以回传的截图。及对应iso种子名称。

安卓的这个客户端yamby不能播放iso格式电影。播放原盘电影（bdmv）可以回传记录，下面是回传截图
![Screenshot_20241119_155942_com hush yamby](https://github.com/user-attachments/assets/e5bb7446-4ebe-4418-8285-805ae53fc89e)

**Comment by kjtsune** [comment]
那就提供bdmv无法回传的日志。

**Comment by frvery** [comment]
> 那就提供bdmv无法回传的日志。

问下，日志去哪里找？

**Comment by kjtsune** [comment]
FAQ 如何反馈

**Comment by frvery** [comment]
> FAQ 如何反馈

you have pressed one
﻿[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:06:26._hide_user_] ['Python path: D:\\Program Files (x86)\\Python\\Python3_hide_user_3\\python.exe']
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:06:26._hide_user_] ['ini path: G:\\PotPlay播放器插件备份\\油猴插件emby调用potplayer\\embyToLocalPlayer\\embyToLocalPlayer_config.ini']
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:06:26.2] Windows-_hide_user__hide_user_-_hide_user_0.0.2263_hide_user_-SP0 Python-3._hide_user_3.0
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:06:26.9] kill 7324 "python" "G:\PotPlay播放器插件备份\油猴插件emby 调用potplayer\embyToLocalPlayer\embyToLocalPlayer.py"
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:06:27.9] G:\PotPlay播放器插件备份\油猴插件emby调用potplayer\embyToLocalPlayer\embyToLocalPlayer.py
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:06:27.9] serving at http://_hide_user_27.0.0._hide_user_:58000
_hide_user_27.0.0._hide_user_ - - [_hide_user_9/Nov/2024 _hide_user_8:06:59] "POST /embyToLocalPlayer/ HTTP/_hide_user_._hide_user_" 200 -
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:06:59._hide_user_] PyScript/2024._hide_user_0.30 UserScript/2024._hide_user__hide_user_.05 Tampermonkey/5.3.2
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:06:59._hide_user_] Mozilla/5.0 (Windows NT _hide_user_0.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/_hide_user_3_hide_user_.0.0.0 Safari/537.36 Edg/_hide_user_3_hide_user_.0.0.0
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:06:59._hide_user_] server=emby/4.8._hide_user_0.0 data['mount_disk_mode']=True
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:06:59._hide_user_] command line: ['D:\\Program Files (x86)\\PotPlayer\\PotPlayerMini64.exe', 'Y:\\硬链接link\\0_hide_user_电影资源\\外语电影\\自杀现场直播 (20_hide_user_0)']
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:06:59._hide_user_] ["_hide_user_92._hide_user_6_mix_host_:39622 match: playlist[enable_host] ['local', '_hide_user_27.0', '_hide_user_92._hide_user_68', '_hide_user_92-_hide_user_68-', 'example.com:8096', '.']"]
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:06:59._hide_user_] ['D:\\Program Files (x86)\\PotPlayer\\PotPlayerMini64.exe', 'Y:\\硬链接link\\0_hide_user_电影资源\\外语电影\\自杀现场直播 (20_hide_user_0)', '/seek=00:00:00']
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:07:_hide_user__hide_user_.8] pot stop, stop_sec=0
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:07:_hide_user__hide_user_.8] skip update progress: key='' _stop_sec=0 not in playlist_data
[_hide_user__hide_user_/_hide_user_9/24 _hide_user_8:07:_hide_user__hide_user_.8] skip update progress: key='PEEPLI LIVE' _stop_sec=762 not in playlist_data


这个可以吗，打开原盘电影，关闭后，没回传，我复制的log里面内容

**Comment by kjtsune** [comment]
因为pot播放bdmv文件夹时候 `/title` 设置pot标题的选项失效。
此时刚好iso文件又内置标题，被pot拿来当标题。
导致标题和emby上的数据无法关联。（文件夹名称和emby自身标题可关联）
`skip update progress: key='PEEPLI LIVE' _stop_sec=762 not in playlist_data`

解决方案：
* 向pot反馈这个问题。
* 不用读盘模式。
* 配合 force_disk_mode_path 选项实现：仅 bdmv 使用非读盘模式。

无关提醒：mpv 无法读盘模式播放 bdmv 文件夹

**Comment by frvery** [comment]
> 因为pot播放bdmv文件夹时候 `/title` 设置pot标题的选项失效。 此时刚好视频文件又内置标题，被pot拿来当标题。 导致标题和emby上的数据无法关联。（文件夹名称和emby自身标题可关联） `skip update progress: key='PEEPLI LIVE' _stop_sec=762 not in playlist_data`
> 
> 解决方案：
> 
>     * 向pot反馈这个问题。
> 
>     * 不用读盘模式。
> 
>     * 配合 force_disk_mode_path 选项实现：仅 bdmv 使用非读盘模式。
> 
> 
> 无关提醒：mpv 无法读盘模式播放 bdmv 文件夹


> 因为pot播放bdmv文件夹时候 `/title` 设置pot标题的选项失效。 此时刚好视频文件又内置标题，被pot拿来当标题。 导致标题和emby上的数据无法关联。（文件夹名称和emby自身标题可关联） `skip update progress: key='PEEPLI LIVE' _stop_sec=762 not in playlist_data`
> 
> 解决方案：
> 
>     * 向pot反馈这个问题。
> 
>     * 不用读盘模式。
> 
>     * 配合 force_disk_mode_path 选项实现：仅 bdmv 使用非读盘模式。
> 
> 
> 无关提醒：mpv 无法读盘模式播放 bdmv 文件夹

谢谢解答，还是用度盘模式兼容性好。关了读盘模式，不仅有些电影模仿不了，MKV格式电影都回传不了观看记录了。。。

**Comment by kjtsune** [comment]
> 不注释掉，一直提示地址关闭

什么原因不降级pot使用？
https://github.com/kjtsune/embyToLocalPlayer/issues/71#issuecomment-2336734496

**Comment by kjtsune** [comment]
结论：
* iso 无法回传，正常现象。
* 读盘模式：
    * pot 播放 bdmv 文件夹，若视频文件内置标题，会回传失败。非读盘模式正常。
    * mpv 自身无法按文件夹播放 bdmv，非读盘模式正常。
* 其他未测试。

**Comment by kjtsune** [comment]
`player_by_path` 根据路径使用特定播放器。
`force_disk_mode_path` 根据路径启用读盘模式。
这两个配置项有助于解决部分问题。
