### ISSUE TITLE
反代怎么用？

### ISSUE THREAD

**Issue by rosspsp** [kjtsune/embyToLocalPlayer#89]
# 网址之间逗号隔开，成对填写。源站, 反代站。
stream_redirect = http://src.src.com, http://reverse.proxy.com, https://src.abc.org, https://reverse.efg.xyz

我的nas上部署有emby的docker，地址192.168.31.150:8096，另外还不熟了负责反代的docker，地址192.168.31.150:9090，想问一下这个stream_redirect应该怎么填写

**Comment by kjtsune** [comment]
不需要写。这个是部署在境外，并且是多台 vps 负载均衡的时候，加速跳转而已。
只有加速作用，不是必要条件。乱写反而可能出问题。
本地本身就快，本选项没用。

**Comment by rosspsp** [comment]
明白了，谢谢
