### ISSUE TITLE
strm文件有的可以顺利启播，有的不可以

### ISSUE THREAD

**Issue by rosspsp** [kjtsune/embyToLocalPlayer#90]
如题，希望优化一下strm的播放，有的可以一次顺利启播，有的不可以，但是可以emby中可以顺利获取到媒体信息，稍微等一会再次播放，可以启播

**Comment by kjtsune** [comment]
看 FAQ 如何反馈。
盲猜因为缺少媒体信息而报错。

**Comment by rosspsp** [comment]
> 看 FAQ 如何反馈。 盲猜因为缺少媒体信息而报错。

<img width="391" alt="image" src="https://github.com/user-attachments/assets/3f6bd28e-8876-4d6b-ae03-ca6761e30e71">
mac没有debug.command文件，需要运行哪个？

**Comment by kjtsune** [comment]
etlp_run.command

**Comment by rosspsp** [comment]
> etlp_run.command
这个视频没有顺利启播，这是运行etlp_run.command后的截图

<img width="1663" alt="image" src="https://github.com/user-attachments/assets/42d3f540-f024-4874-9258-aa0e1f92aa46">

**Comment by rosspsp** [comment]
第一次播放，没有顺利启播，但是获取到了视频媒体信息，稍等一会儿之后，在此播放，顺利启播，下面是截图
<img width="1663" alt="image" src="https://github.com/user-attachments/assets/ac0b8d01-849d-429c-8460-9a46bc4f7abf">

**Comment by kjtsune** [comment]
这是 strm 和 播放器的兼容问题。不知道为什么会 403

https://github.com/sjtuross/StrmAssistant
应该可以通过这个项目扫描出视频信息来解决，我没用过。

**Comment by rosspsp** [comment]
> 这是 strm 和 播放器的兼容问题。不知道为什么会 403
> 
> https://github.com/sjtuross/StrmAssistant 应该可以通过这个项目扫描出视频信息来解决，我没用过。

我试试，谢谢大佬

**Comment by kjtsune** [comment]
报错是由 mpv 抛出的，非本脚本。
建议检查直链配置或向对应项目提出反馈。
