### ISSUE TITLE
在剧集标题有变化的情况下马上点播放 回传会失效

### ISSUE THREAD

**Issue by verygoodlee** [kjtsune/embyToLocalPlayer#93]
比如右键刷新媒体元数据刮削出了新标题，然后点播放，由于油猴脚本的剧集信息缓存，美化标题用的还是旧标题，
猜测回传功能应该用到了标题，后台查到的剧集信息是新标题，导致匹配不上，回传失效。

简单复现的话，就右键编辑元数据手动改个标题，改完点播放。

要完全修复的话可能要去除缓存吧，启播速度可能慢一点点，如果差距很小倒是可以考虑去掉缓存，
不算很严重的问题，改完标题手动刷新下网页就可以避免，不打算修复的话在README里提醒一下也行。

**Comment by kjtsune** [comment]
简单修了下，过些天没问题再同步油猴。
