### ISSUE TITLE
大佬，可以添加对strm的支持吗？

### ISSUE THREAD

**Issue by rosspsp** [kjtsune/embyToLocalPlayer#94]
直接播放strm文件中的内容，例如，strm文件中的内容是“http://192.168.31.150:9527/d/b5pa1gjxg338smg?/MIDV-166.mp4”，还有路径形式的，直接用strm中的这个内容，不走emby

**Comment by kjtsune** [comment]
更新
https://github.com/kjtsune/embyToLocalPlayer/blob/977c9ab859a94aee9d462ef1447c1bf8baa78b2b/embyToLocalPlayer_config.ini#L117-L118

**Comment by rosspsp** [comment]
> 更新
> 
> https://github.com/kjtsune/embyToLocalPlayer/blob/977c9ab859a94aee9d462ef1447c1bf8baa78b2b/embyToLocalPlayer_config.ini#L117-L118

大佬，有报错，启动时python意外退出，启动后，播放视频，报下面的错
Error parsing option focus-on (option not found)
Setting commandline option --focus-on=open failed.

**Comment by kjtsune** [comment]
https://github.com/kjtsune/embyToLocalPlayer/issues/91

**Comment by rosspsp** [comment]
> #91

昨天已更新utils文件夹下所有的文件，players.py中已添加cmd.append('--focus-on=open')

**Comment by rosspsp** [comment]
我明白了，mpv版本我是不是要更新到0.38？0.37下players.py是不是应该改回cmd.append('--focus-on-open')

**Comment by rosspsp** [comment]
更新mpv后，测试通过，mpv版本0.39

**Comment by kjtsune** [comment]
> 都会走strm

已经修复
> player_by_path配置项失效

日志

**Comment by rosspsp** [comment]
经测试，已经修复，下面是player_by_path配置项失效的日志
<img width="1551" alt="image" src="https://github.com/user-attachments/assets/deae72e8-78b8-41d4-818b-4447d79a9939">

**Comment by kjtsune** [comment]
适配了

**Comment by kjtsune** [comment]
macOS 播放器窗口不在前台的问题，可能配合 AppleScript 可以解决。但现在没环境测试。
可以重新提 issue 等别人适配。
